### ISSUE TITLE
object_url can't support put object

### ISSUE THREAD

**Issue by vip30** [ug0/aliyun_oss#20]
https://github.com/ug0/aliyun_oss/blob/7d335a59898f5ee1ef5f57a04fd02a3a22f8f066/lib/aliyun_oss/object.ex#L206-L219

As currently you hardcoded to GET, and for put object also need to pass the content type in the header

`When you put object with signatureUrl ,you need to pass Content-Type`

Can we add one more overload function to handle this case?

If you have any idea, please let me know

**Comment by ug0** [comment]
Oh, I didn't think of the that when I wrote the `object_url` fucntion. Actually I just wanted a convenient way to expose the object URL for downloading.

I think we can add a new function `signed_url`(or if you have a better name) to support all the features described in the official [doc](https://help.aliyun.com/document_detail/31952.html?spm=a2c4g.11186623.6.1565.4bc060e82gasBd). 
```elixir
def signed_url(bucket, object, expires, method \\ "GET", headers \\ ${}, sub_resources \\ %{}) do
end
```

What do you think?

**Comment by vip30** [comment]
LGTM

Will you commit this changes?

Thanks

**Comment by ug0** [comment]
I'll try to get this done by today or tomorrow.

**Comment by ug0** [comment]
[This](#21) has been implemented and merged to master. While I was coding, I realized maybe I shouldn't limit `signed_url` to only objects. But I don't want to just define another `Bucket.signed_url` function because I think that's a bit redundant and there should be a better way.
Eventually I decide to just release a new version with `Object.signed_url` for now. 

However, if you look at the [implementation](https://github.com/ug0/aliyun_oss/blob/master/lib/aliyun_oss/object.ex#L207-L219) of `Object.signed_url`, you can easilly build any signed URL for other APIs by using `Request.signed_query_url`. For example:

```elixir
  # Signed URL for GetBucket
   %{
      verb: "GET",
      host: "#{bucket}.#{endpoint()}",
      path: "/",
      resource: "/#{bucket}/",
      sub_resources: %{},
      headers: %{"Content-Type" => ""},
      expires: expires
    }
    |> Request.build()
    |> Request.signed_query_url()
```


```elixir
  # Signed URL for PutBucketAcl
   %{
      verb: "PUT",
      host: "#{bucket}.#{endpoint()}",
      path: "/",
      resource: "/#{bucket}/",
      sub_resources: %{"acl" => nil},
      headers: %{"Content-Type" => "text/plain;charset=UTF-8", "x-oss-acl" => "private"},
      expires: expires
    }
    |> Request.build()
    |> Request.signed_query_url()
```


```elixir
  # Signed URL for GetBucket
   %{
      verb: "GET",
      host: endpoint(),
      path: "/",
      resource: "/",
      sub_resources: %{"Content-Type" => ""},
      headers: %{},
      expires: expires
    }
    |> Request.build()
    |> Request.signed_query_url()
```

**Comment by ug0** [comment]
v0.5.0 has been released.
